create extension if not exists pgcrypto;

create type outreach_status as enum ('NOT_CONTACTED','REQUEST_SENT','REQUEST_ACCEPTED','INITIAL_DM_SENT','FOLLOW_UP_1','FOLLOW_UP_2','FOLLOW_UP_3','RESPONDED','IN_CONVERSATION','POSITIVE_REPLY','QUALIFICATION','CALL_PROPOSED','CALL_BOOKED','CALL_ATTENDED','NO_SHOW','OPPORTUNITY','PROPOSAL_SENT','NEGOTIATION','WON','LOST','NOT_NOW','NOT_INTERESTED','DECLINED_SERVICE','WRONG_PERSON','WRONG_ICP','DO_NOT_CONTACT');
create type campaign_status as enum ('draft','active','paused','completed','archived');

create table profiles (id uuid primary key references auth.users on delete cascade, full_name text, timezone text not null default 'Asia/Kolkata', base_currency text not null default 'USD', daily_execution_target numeric not null default 100, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table companies (id uuid primary key default gen_random_uuid(), name text not null, website text, linkedin_url text, industry text, employee_count int, location text, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table prospects (id uuid primary key default gen_random_uuid(), owner_id uuid not null references profiles(id) on delete cascade, first_name text, last_name text, full_name text not null, company_id uuid references companies(id), title text, linkedin_url text, email text, phone text, industry text, location text, source text, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create unique index prospects_owner_linkedin_idx on prospects(owner_id, lower(regexp_replace(coalesce(linkedin_url,''), '/$',''))); create index prospects_owner_name_idx on prospects(owner_id, full_name);
create table campaigns (id uuid primary key default gen_random_uuid(), owner_id uuid not null references profiles(id) on delete cascade, name text not null, description text, icp text, offer text, channel text, status campaign_status not null default 'draft', start_date date, end_date date, daily_outreach_target int not null default 20, daily_followup_target int not null default 25, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table campaign_members (id uuid primary key default gen_random_uuid(), campaign_id uuid not null references campaigns(id) on delete cascade, prospect_id uuid not null references prospects(id) on delete cascade, status outreach_status not null default 'NOT_CONTACTED', initial_message text, initial_contact_at timestamptz, last_contact_at timestamptz, next_action_at timestamptz, next_action_type text, priority_score numeric not null default 0, reply_state text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(campaign_id, prospect_id));
create table touchpoints (id uuid primary key default gen_random_uuid(), owner_id uuid not null references profiles(id) on delete cascade, prospect_id uuid references prospects(id) on delete cascade, campaign_id uuid references campaigns(id) on delete set null, type text not null, channel text not null, message text, sent_at timestamptz not null default now(), created_by uuid references profiles(id), metadata jsonb not null default '{}'); create index touchpoints_owner_sent_idx on touchpoints(owner_id, sent_at desc);
create table replies (id uuid primary key default gen_random_uuid(), owner_id uuid not null references profiles(id) on delete cascade, prospect_id uuid not null references prospects(id) on delete cascade, campaign_id uuid references campaigns(id) on delete set null, touchpoint_id uuid references touchpoints(id) on delete set null, message text not null, received_at timestamptz not null default now(), classification text, sentiment text, positive boolean not null default false, requires_response boolean not null default true, response_status text not null default 'needs_response', responded_at timestamptz, notes text);
create table tasks (id uuid primary key default gen_random_uuid(), owner_id uuid not null references profiles(id) on delete cascade, prospect_id uuid references prospects(id) on delete cascade, campaign_id uuid references campaigns(id) on delete set null, task_type text not null, title text not null, description text, priority int not null default 0, due_at timestamptz, status text not null default 'open', points numeric not null default 0, completed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table activity_logs (id uuid primary key default gen_random_uuid(), owner_id uuid not null references profiles(id) on delete cascade, prospect_id uuid references prospects(id) on delete set null, event_type text not null, occurred_at timestamptz not null default now(), metadata jsonb not null default '{}');

alter table profiles enable row level security; alter table companies enable row level security; alter table prospects enable row level security; alter table campaigns enable row level security; alter table campaign_members enable row level security; alter table touchpoints enable row level security; alter table replies enable row level security; alter table tasks enable row level security; alter table activity_logs enable row level security;
create policy "owner profiles" on profiles for all using (id = auth.uid()) with check (id = auth.uid());
create policy "owner companies" on companies for all using (exists(select 1 from profiles p where p.id=auth.uid())) with check (exists(select 1 from profiles p where p.id=auth.uid()));
create policy "owner prospects" on prospects for all using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "owner campaigns" on campaigns for all using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "owner campaign members" on campaign_members for all using (exists(select 1 from campaigns c where c.id=campaign_id and c.owner_id=auth.uid())) with check (exists(select 1 from campaigns c where c.id=campaign_id and c.owner_id=auth.uid()));
create policy "owner touchpoints" on touchpoints for all using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "owner replies" on replies for all using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "owner tasks" on tasks for all using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "owner logs" on activity_logs for all using (owner_id = auth.uid()) with check (owner_id = auth.uid());
